spring:
    # 数据库连接
    datasource:
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bill_management?characterEncoding=utf-8&useSSL=false
            user: root
            password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.doudou.bill.orm.model  # 注意：对应实体类的路径
  configuration:
      mapUnderscoreToCamelCase: true