server:
    port: 10001
spring:
    # 数据库连接
    datasource:
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/bill_management?characterEncoding=utf-8&useSSL=false
            username: wangcai
            password: 123456

    redis:
      host: localhost
      port: 6379
      database: 0
      password:

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.doudou.bill.orm.model  # 注意：对应实体类的路径
  configuration:
      mapUnderscoreToCamelCase: true


#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
spring.devtools.restart.additional-paths: src/main/resources
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: WEB-INF/**